global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'spring-apps'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: 
          - 'gateway:8080'
          - 'booking:8080'
          - 'session:8080'
          - 'hotel:8080'
          - 'loyalty:8080'
          - 'payment:8080'
          - 'report:8080'

rule_files:
  - alerts.yml